### ISSUE TITLE
query by collection

### ISSUE THREAD

**Issue by DavidGarfinkle** [ELVIS-Project/cbsmr-patternfinder#27]
users should be able to toggle for which collection they are searching over

**Comment by DavidGarfinkle** [comment]
this already exists #15

**Comment by vigliensoni** [comment]
Download the Bach chorales in **kern format from https://github.com/craigsapp/bach-370-chorales and upload them to the app.

**Comment by DavidGarfinkle** [comment]
bach chorales have been added
