### ISSUE TITLE
Increase maximum receiving message size.

### ISSUE THREAD

**Issue by vigliensoni** [ELVIS-Project/cbsmr-patternfinder#32]
Melodic queries (such as http://132.206.14.238/search?query=**kern%0D%0A*clefG2%0D%0A*k%5B%5D%0D%0A%3D-%0D%0A4c+%0D%0A4d+%0D%0A4e+%0D%0A4f+%0D%0A4g%0D%0A&rpp=5&page=0&tnps=-12%2C12&intervening=0%2C0&inexact=0%2C0) return messages that are larger than the GRPC default of 4MB.

```failed to search: <_Rendezvous of RPC that terminated with: status = StatusCode.RESOURCE_EXHAUSTED details = "Received message larger than max (5418422 vs. 4194304)" debug_error_string = "{"created":"@1567112503.150641370","description":"Received message larger than max (5418422 vs. 4194304)","file":"src/core/ext/filters/message_size/message_size_filter.cc","file_line":190,"grpc_status":8}" >```

We should increase the maximum: 

https://godoc.org/google.golang.org/grpc#MaxRecvMsgSize

**Comment by DavidGarfinkle** [comment]
the proper solution here would be to make it a gRPC streaming service rather than a one-message response

but for now I've increased the maximum message size to 1GB
