### ISSUE TITLE
Ajax request getting wrong excerpt measures

### ISSUE THREAD

**Issue by DavidGarfinkle** [ELVIS-Project/cbsmr-patternfinder#34]
http://132.206.14.238/search?query=**kern%0D%0A*clefG2%0D%0A*k%5B%5D%0D%0A%3D-%0D%0A4c+4e+4a+4cc%0D%0A4B-+f+b-+dd&rpp=5&page=0&tnps=0%2C12&intervening=0%2C12&inexact=0%2C1&collection=2

puts measure 26 and 27 from pid 5683 even though the excerpt URL asks for measures 1 and 2

**Comment by DavidGarfinkle** [comment]
this was an issue with AJAX excerpt rendering filling in the incorrect panel. it was patched

**Comment by vigliensoni** [comment]
Isn't this an indexing issue? See the returned excerpt:

<img width="858" alt="Screen Shot 2019-09-02 at 9 26 50 PM" src="https://user-images.githubusercontent.com/492229/64137854-7c0eaa80-cdc8-11e9-924d-b99f34c32f31.png">
