### ISSUE TITLE
Finish container deployment

### ISSUE THREAD

**Issue by vigliensoni** [ELVIS-Project/cbsmr-patternfinder#4]
The containers have to be finished, tested, and deployed to our development environment. 

- [x] Implement Nginx service
- [ ] Populate the index database
- [ ] Deploy all containers and services to dev environment

**Comment by DavidGarfinkle** [comment]
This was solved on branch `dockerlayers` by making a number of refactoring changes to the flask `Dockerfile` including one of Alex's suggestions to use a `debian` base image rather than `alpine`
Not sure in the end what the exact problem was, but, POST requests are working on `132.206.14.238:80`
