### ISSUE TITLE
Fix Pagination

### ISSUE THREAD

**Issue by vigliensoni** [ELVIS-Project/cbsmr-patternfinder#5]
Pagination is already implemented in the URL, but we need to add buttons in the UI to allow users to navigate through the results.

**Comment by DavidGarfinkle** [comment]
Pagination needs to be tested, `rpp` needs a dropdown list in the front-end, and `rpp`/`page` need constraints so you can't request results beyond the total number of occurrences

**Comment by DavidGarfinkle** [comment]
don't have a `Previous` button on page 0

**Comment by DavidGarfinkle** [comment]
Show the total number of pages

**Comment by vigliensoni** [comment]
Actually, pagination should behave the same way that any pagination.

**Comment by DavidGarfinkle** [comment]
including first, last buttons

**Comment by vigliensoni** [comment]
Check some examples:

![Screen Shot 2019-08-22 at 2 40 32 PM](https://user-images.githubusercontent.com/492229/63540835-e0895a00-c4ea-11e9-90ed-64e23337f055.png)


https://www.smashingmagazine.com/2007/11/pagination-gallery-examples-and-good-practices/

**Comment by DavidGarfinkle** [comment]
looking at https://pythonhosted.org/Flask-paginate/

**Comment by vigliensoni** [comment]
Pagination button logic not working properly (app crashes) 

`(http://132.206.14.238/search?query=%2A%2Akern%0D%0A%2AclefG2%0D%0A%2Ak%5B%5D%0D%0A%3D-%0D%0A4c+4e+4a+4cc%0D%0A4B-+f+b-+dd&page=1&rpp=5&tnps=0&tnps=0&intervening=0&intervening=0)`

This happens because `tnps` and `intervining` parameters are duplicated

**Comment by DavidGarfinkle** [comment]
added a resultts per page dropdown to the front end
