### ISSUE TITLE
Add parameters for search

### ISSUE THREAD

**Issue by vigliensoni** [ELVIS-Project/cbsmr-patternfinder#6]
Search parameters (i.e., number of intervening notes and type of search) is currently fix. The user should be able to choose these values. 

The baseline is what we currently have in the Patternfinder app.

**Comment by DavidGarfinkle** [comment]
backend was implemented and merged into master last week

two filters supported: `tnps` and `intervening`

**Comment by DavidGarfinkle** [comment]
front-end is currently being implemented on branch `filter`

UI works, now it needs to be merged

then some integration tests need to be written with varying filter settings

**Comment by DavidGarfinkle** [comment]
include filter for number of notes

**Comment by vigliensoni** [comment]
When user toggles inexact matches provide feedback to user, so that they understand why there are so many occurrences.

**Comment by DavidGarfinkle** [comment]
filters included. next step is to decide on the UI experience. out of scope for this issue
